routes/web.php
<?php
  
use Illuminate\Support\Facades\Route;
  
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\PermissionController;
  
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
  

Route::resource('page', 'PageController');
Route::resource('category', 'CategoryController');
Route::resource('post', 'PostController');
// Route::get('/', function () {
//     return view('welcome');
// });
  
Auth::routes();
  
Route::get('/home', [HomeController::class, 'index'])->name('home');
  
Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::resource('permissions', PermissionController::class);
    Route::resource('products', ProductController::class);
});

Route::get('/{any}', [HomeController::class, 'index'])->where('any', '.*');
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Http/Controllers/PermissionController.php
<?php
namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Permission;
use Spatie\Permission\Models\Role;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Validation\Rule;
use Notification;
use GuzzleHttp\Client;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Validator;
use Yajra\DataTables\Facades\DataTables;
use \DateTime;
use Maatwebsite\Excel\Facades\Excel;
use App\Exports\ReportExport;
use App\Exports\ExportLandinventory;
Use \Carbon\Carbon;
Use Redirect;
Use Session;

class PermissionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        
     // return dd($table_list);
     // exit();

          $permissions = Permission::orderBy('id','DESC')->paginate(15);
        return view('Admin.Permission.index',compact('permissions'))
            ->with('i', ($request->input('page', 1) - 1) * 5);


    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {



         $permission = Permission::get();
        return view('Admin.Permission.create',compact('permission'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
              $this->validate($request, [
            'key' => 'required|unique:roles,name',
            // 'key' => 'required',
        ]);

    $name = str_replace('_', ' ', $request->input('key'));
    $name = ucwords($name);

    $data = [
        'name' =>$request->input('key'),
        'key' =>$name,
        'guard_name' =>'web',
        'table_name' =>$request->input('table_name'),
    ];

        $role = Permission::create($data);
        // $role->syncPermissions($request->input('permission'));
    
        return redirect()->route('permissions.index')
                        ->with('success','Permission Added Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($name)
    {
             $permission_edit = DB::table('permissions')->where('name',$name)->first();
        $permission = Permission::get();
        // $rolePermissions = DB::table("role_has_permissions")->where("role_has_permissions.permission_id",$id)
        //     ->pluck('role_has_permissions.permission_id')
        //     ->all();

        // return dd($permission_edit);

             return view('Admin.Permission.edit',compact('permission_edit','permission','name'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
          $this->validate($request, [
            'permission' => 'required',
        ]);


        $data = array(
            'name' =>$request->input('permission'),
            'table_name' =>$request->input('table_name')
        );


        $affected = DB::table('permissions')
              ->where('name',$id)
              ->update($data);
    
        // $role->syncPermissions($request->input('permission'));
    
        return redirect()->route('permissions.index')
                        ->with('success','Permission Updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
         Permission::find($id)->delete();
        return redirect()->route('permissions.index')
                        ->with('danger','Permission Deleted successfully');
    }
}

resources/views/Admin/Permission/create.blade.php
@extends('Admin.master')
@section('main_content')
<div class="inner-wrapper">
<section role="main" class="content-body">
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Create New Permission</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('permissions.index') }}"> Back</a>
        </div>
    </div>
</div>


@if (count($errors) > 0)
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
        @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
        </ul>
    </div>
@endif


{!! Form::open(array('route' => 'permissions.store','method'=>'POST')) !!}
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Key:</strong>
            {!! Form::text('key', null, array('placeholder' => 'Key','class' => 'form-control')) !!}
        </div>
        <div class="form-group">
            <strong>Table Name:</strong>
            {!! Form::text('table_name', null, array('placeholder' => 'Table Name','class' => 'form-control')) !!}
         
        </div>
        <div class="form-group">
            <strong>Is User Defined *:</strong>
            {!! Form::text('is_user_defined', null, array('placeholder' => 'User Defined','class' => 'form-control')) !!}
        </div>
    </div>
{{--     <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Permission:</strong>
            <br/>
            @foreach($permission as $value)
                <label>{{ Form::checkbox('permission[]', $value->id, false, array('class' => 'name')) }}
                {{ $value->name }}</label>
            <br/>
            @endforeach
        </div>
    </div> --}}
    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</div>
{!! Form::close() !!}

@endsection

resources/views/Admin/Permission/edit.blade.php
@extends('Admin.master')
@section('main_content')
<div class="inner-wrapper">
<section role="main" class="content-body">
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Edit Permission</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('permissions.index') }}"> <i class="fa fa-arrow-left"></i> Back</a>
        </div>
    </div>
</div>


@if (count($errors) > 0)
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
        @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
        </ul>
    </div>
@endif


{!! Form::model($permission_edit, ['method' => 'PATCH','route' => ['permissions.update', $name]]) !!}
<div class="row">

    <div class="col-xs-12 col-sm-12 col-md-12">
         <div class="col-xs-12 col-sm-12 col-md-12">
    
        <div class="form-group">
            <strong>Table Name:</strong>
            @if(!empty($permission_edit->table_name))
            {!! Form::text('table_name', $permission_edit->table_name, array('placeholder' => 'Table Name','class' => 'form-control')) !!}
            @else
            {!! Form::text('table_name', null, array('placeholder' => 'Table Name','class' => 'form-control')) !!}

            @endif
         
        </div>
        <div class="form-group">
            <strong>Is User Defined *:</strong>
            {!! Form::text('is_user_defined', null, array('placeholder' => 'User Defined','class' => 'form-control')) !!}
        </div>
    </div>
        <div class="form-group">
            <strong>Permission:</strong>
            <br>
            <br/>
            @foreach($permission as $value)
                <label>
                   {{--  {{ Form::checkbox('permission[]', $value->name, in_array($value->name, $id) ? true : false, array('class' => 'name')) }} --}}

                     <input type="checkbox" id="permission-{{$value->id}}" name="permission" class="permission" data-permission-name="{{$value->name}}" value="{{$value->name}}" @if($value->name == $name ){{ 'checked'}}@else {{ false}}@endif>

                {{ $value->name }}</label>
            <br/>
            @endforeach
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</div>
{!! Form::close() !!}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
        $('document').ready(function () {
            // $('.toggleswitch').bootstrapToggle();

            // $('.permission-group').on('click', function(){
            //     // alert();
            //     $('.the-permission').find("input[type='checkbox']").prop('checked', true);
            // });

            $('.permission').on('click', function(){

                 let check_permission_name = $(this).val();
                 let permission_name = $(this).data('permission-name');

                 if (permission_name = check_permission_name) {

                 // alert(check_permission_name);

                $('.permissions').find("input[type='checkbox']").prop('checked', true);
                return false;
                 }
                 else{

                $('.permissions').find("input[type='checkbox']").prop('checked', false);
                return false;
                 }
            });


        });
    </script>

@endsection

resources/views/Admin/Permission/index.blade.php
@extends('Admin.master')
@section('main_content')
<div class="inner-wrapper">
<section role="main" class="content-body">
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Permission Management</h2>
        </div>
        <div class="pull-right">
        @can('permission-create')
            <a class="btn btn-success" href="{{ route('permissions.create') }}"> <i class="fa fa-plus"></i>    Add Permission</a>
            @endcan
        </div>
    </div>
</div>


@if ($message = Session::get('success'))
    <div class="alert alert-success">
        <p>{{ $message }}</p>
    </div>
@endif
@if ($message = Session::get('danger'))
    <div class="alert alert-danger">
        <p>{{ $message }}</p>
    </div>
@endif

<section class="panel">
                            <header class="panel-heading">
                                <div class="panel-actions">
                                    <a href="#" class="fa fa-caret-down"></a>
                                    <a href="#" class="fa fa-times"></a>
                                </div>
                        
                               
                            </header>
                            <div class="panel-body">
    <table class="table table-bordered table-striped mb-none" id="datatable-default">
<thead>
      <tr>
     <th>No</th>
     <th>Name</th>
     <th width="280px">Action</th>
  </tr>
</thead>
  <tbody>
    @foreach ($permissions as $key => $permission)
    <tr>
        <td>{{ ++$i }}</td>
        <td>{{ $permission->name }}</td>
        <td>
          {{--   <a class="btn btn-info" href="{{ route('permissions.show',$permission->id) }}"> <i class="fa fa-eye"></i> Show</a> --}}
            @can('permission-edit')
                <a class="btn btn-primary" href="{{ route('permissions.edit',$permission->name) }}"><i class="fa fa-edit"></i> Edit</a>
            @endcan
            @can('permission-delete')

                {!! Form::open(['method' => 'DELETE','route' => ['permissions.destroy', $permission->id],'style'=>'display:inline']) !!}
                    <i class="fa fa-trash-o"></i> 
                     {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
                {!! Form::close() !!}
            @endcan
        </td>
    </tr>
    @endforeach
  </tbody>
</table>
</section>
</div>
</div>
</div>
</section>
{!! $permissions->render() !!}

@endsection