routes/web.php
<?php
  
use Illuminate\Support\Facades\Route;
  
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\PermissionController;
  
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
  

Route::resource('page', 'PageController');
Route::resource('category', 'CategoryController');
Route::resource('post', 'PostController');
// Route::get('/', function () {
//     return view('welcome');
// });
  
Auth::routes();
  
Route::get('/home', [HomeController::class, 'index'])->name('home');
  
Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::resource('permissions', PermissionController::class);
    Route::resource('products', ProductController::class);
});

Route::get('/{any}', [HomeController::class, 'index'])->where('any', '.*');
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/Admin/common/footer.blade.php
		<!-- Vendor -->
		<script src="{{ asset('/admin_resource/')}}/assets/vendor/jquery/jquery.js"></script>
		<script src="{{ asset('/admin_resource/')}}/assets/vendor/jquery-browser-mobile/jquery.browser.mobile.js"></script>
		<script src="{{ asset('/admin_resource/')}}/assets/vendor/bootstrap/js/bootstrap.js"></script>
		<script src="{{ asset('/admin_resource/')}}/assets/vendor/nanoscroller/nanoscroller.js"></script>
		<script src="{{ asset('/admin_resource/')}}/assets/vendor/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
		<script src="{{ asset('/admin_resource/')}}/assets/vendor/magnific-popup/magnific-popup.js"></script>
		<script src="{{ asset('/admin_resource/')}}/assets/vendor/jquery-placeholder/jquery.placeholder.js"></script>
		
		<!-- Specific Page Vendor -->
		<script src="{{ asset('/admin_resource/')}}/assets/vendor/jquery-ui/js/jquery-ui-1.10.4.custom.js"></script>
		<script src="{{ asset('/admin_resource/')}}/assets/vendor/jquery-ui-touch-punch/jquery.ui.touch-punch.js"></script>
		<script src="{{ asset('/admin_resource/')}}/assets/vendor/jquery-appear/jquery.appear.js"></script>
		<script src="{{ asset('/admin_resource/')}}/assets/vendor/bootstrap-multiselect/bootstrap-multiselect.js"></script>
		<script src="{{ asset('/admin_resource/')}}/assets/vendor/jquery-easypiechart/jquery.easypiechart.js"></script>
		<script src="{{ asset('/admin_resource/')}}/assets/vendor/flot/jquery.flot.js"></script>
		<script src="{{ asset('/admin_resource/')}}/assets/vendor/flot-tooltip/jquery.flot.tooltip.js"></script>
		<script src="{{ asset('/admin_resource/')}}/assets/vendor/flot/jquery.flot.pie.js"></script>
		<script src="{{ asset('/admin_resource/')}}/assets/vendor/flot/jquery.flot.categories.js"></script>
		<script src="{{ asset('/admin_resource/')}}/assets/vendor/flot/jquery.flot.resize.js"></script>
		<script src="{{ asset('/admin_resource/')}}/assets/vendor/jquery-sparkline/jquery.sparkline.js"></script>
		<script src="{{ asset('/admin_resource/')}}/assets/vendor/raphael/raphael.js"></script>
		<script src="{{ asset('/admin_resource/')}}/assets/vendor/morris/morris.js"></script>
		<script src="{{ asset('/admin_resource/')}}/assets/vendor/gauge/gauge.js"></script>
		<script src="{{ asset('/admin_resource/')}}/assets/vendor/snap-svg/snap.svg.js"></script>
		<script src="{{ asset('/admin_resource/')}}/assets/vendor/liquid-meter/liquid.meter.js"></script>
		<script src="{{ asset('/admin_resource/')}}/assets/vendor/jqvmap/jquery.vmap.js"></script>
		<script src="{{ asset('/admin_resource/')}}/assets/vendor/jqvmap/data/jquery.vmap.sampledata.js"></script>
		<script src="{{ asset('/admin_resource/')}}/assets/vendor/jqvmap/maps/jquery.vmap.world.js"></script>
		<script src="{{ asset('/admin_resource/')}}/assets/vendor/jqvmap/maps/continents/jquery.vmap.africa.js"></script>
		<script src="{{ asset('/admin_resource/')}}/assets/vendor/jqvmap/maps/continents/jquery.vmap.asia.js"></script>
		<script src="{{ asset('/admin_resource/')}}/assets/vendor/jqvmap/maps/continents/jquery.vmap.australia.js"></script>
		<script src="{{ asset('/admin_resource/')}}/assets/vendor/jqvmap/maps/continents/jquery.vmap.europe.js"></script>
		<script src="{{ asset('/admin_resource/')}}/assets/vendor/jqvmap/maps/continents/jquery.vmap.north-america.js"></script>
		<script src="{{ asset('/admin_resource/')}}/assets/vendor/jqvmap/maps/continents/jquery.vmap.south-america.js"></script>
		
		<!-- Theme Base, Components and Settings -->
		<script src="{{ asset('/admin_resource/')}}/assets/javascripts/theme.js"></script>
		
		<!-- Theme Custom -->
		<script src="{{ asset('/admin_resource/')}}/assets/javascripts/theme.custom.js"></script>
		
		<!-- Theme Initialization Files -->
		<script src="{{ asset('/admin_resource/')}}/assets/javascripts/theme.init.js"></script>


		<!-- Examples -->
		<script src="{{ asset('/admin_resource/')}}/assets/javascripts/dashboard/examples.dashboard.js"></script>

		<!-- Specific Page Vendor -->
		<script src="{{ asset('/admin_resource/')}}/assets/vendor/jquery-validation/jquery.validate.js"></script>
		
		<script src="{{ asset('/admin_resource/')}}/assets/vendor/jquery-datatables/media/js/jquery.dataTables.js"></script>
	<script src="{{ asset('/admin_resource/')}}/assets/vendor/jquery-datatables/extras/TableTools/js/dataTables.tableTools.min.js"></script>
		<script src="{{ asset('/admin_resource/')}}/assets/vendor/jquery-datatables-bs3/assets/js/datatables.js"></script>


	</body>
</html>

resources/views/Admin/common/header.blade.php
<!doctype html>
<html class="fixed">
	<head>
		<!-- Basic -->
		<meta charset="UTF-8">
		<title>Dashboard</title>
		<meta name="keywords" content="HTML5 Admin Template"/>
		<meta name="description" content="JSOFT Admin - Responsive HTML5 Template">
		<meta name="author" content="JSOFT.net">
		<!-- Mobile Metas -->
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

		<!-- Web Fonts  -->
		<link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800|Shadows+Into+Light" rel="stylesheet" type="text/css">

		<!-- Vendor CSS -->
<link rel="stylesheet" href="{{ asset('/admin_resource/')}}/assets/vendor/bootstrap/css/bootstrap.css">

	<link rel="stylesheet" href="{{ asset('/admin_resource/assets/vendor/font-awesome/css/font-awesome.css')}}" />
	<link rel="stylesheet" href="{{ asset('/admin_resource/assets/vendor/magnific-popup/magnific-popup.css')}}" />
	<link rel="stylesheet" href="{{ asset('/admin_resource/assets/vendor/bootstrap-datepicker/css/datepicker3.css')}}" />

		<link rel="stylesheet" href="{{ asset('/admin_resource/')}}/assets/vendor/jquery-datatables-bs3/assets/css/datatables.css" />

		<!-- Specific Page Vendor CSS -->
	<link rel="stylesheet" href="{{ asset('/admin_resource/assets/vendor/jquery-ui/css/ui-lightness/jquery-ui-1.10.4.custom.css')}}" />
		<link rel="stylesheet" href="{{ asset('/admin_resource/')}}/assets/vendor/bootstrap-multiselect/bootstrap-multiselect.css" />
		<link rel="stylesheet" href="{{ asset('/admin_resource/')}}/assets/vendor/morris/morris.css" />

		<!-- Theme CSS -->
		<link rel="stylesheet" href="{{ asset('/admin_resource/')}}/assets/stylesheets/theme.css" />

		<!-- Skin CSS -->
		<link rel="stylesheet" href="{{ asset('/admin_resource/')}}/assets/stylesheets/skins/default.css" />

		<!-- Theme Custom CSS -->
		<link rel="stylesheet" href="{{ asset('/admin_resource/')}}/assets/stylesheets/theme-custom.css">
		<link rel="stylesheet" href="{{ asset('/admin_resource/')}}/assets/vendor/font-awesome/css/font-awesome.css" />
  <script src="https://cdn.tiny.cloud/1/yfnw3w8klca6fy8agnjalelwtx9hgo92c7q5fq7kz47pjqgl/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
		<!-- Head Libs -->
		<script src="{{ asset('/admin_resource/')}}/assets/vendor/modernizr/modernizr.js"></script>




	</head>
	<body>
		<section class="body">

			<!-- start: header -->
			<header class="header">
				<div class="logo-container">
					<a href="{{ url('/')}}" class="logo">
						<img src="{{ asset('/admin_resource/')}}/assets/images/logo.png" height="35" alt="Logo" />
					</a>
					<div class="visible-xs toggle-sidebar-left" data-toggle-class="sidebar-left-opened" data-target="html" data-fire-event="sidebar-left-opened">
						<i class="fa fa-bars" aria-label="Toggle sidebar"></i>
					</div>
				</div>
			
				<!-- start: search & user box -->
				<div class="header-right">
			
					<form action="pages-search-results.html" class="search nav-form">
						<div class="input-group input-search">
							<input type="text" class="form-control" name="q" id="q" placeholder="Search...">
							<span class="input-group-btn">
								<button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
							</span>
						</div>
					</form>
			
					<span class="separator"></span>
			
					<ul class="notifications">
						<li>
							<div class="dropdown-menu notification-menu large">
								<div class="content">
									<ul>
										<li>
											<p class="clearfix mb-xs">
												<span class="message pull-left">Generating Sales Report</span>
												<span class="message pull-right text-dark">60%</span>
											</p>
											<div class="progress progress-xs light">
												<div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;"></div>
											</div>
										</li>
			
										<li>
											<p class="clearfix mb-xs">
												<span class="message pull-left">Importing Contacts</span>
												<span class="message pull-right text-dark">98%</span>
											</p>
											<div class="progress progress-xs light">
												<div class="progress-bar" role="progressbar" aria-valuenow="98" aria-valuemin="0" aria-valuemax="100" style="width: 98%;"></div>
											</div>
										</li>
			
										<li>
											<p class="clearfix mb-xs">
												<span class="message pull-left">Uploading something big</span>
												<span class="message pull-right text-dark">33%</span>
											</p>
											<div class="progress progress-xs light mb-xs">
												<div class="progress-bar" role="progressbar" aria-valuenow="33" aria-valuemin="0" aria-valuemax="100" style="width: 33%;"></div>
											</div>
										</li>
									</ul>
								</div>
							</div>
						</li>
						<li>
							<a href="#" class="dropdown-toggle notification-icon" data-toggle="dropdown">
								<i class="fa fa-envelope"></i>
								<span class="badge">4</span>
							</a>
			
							<div class="dropdown-menu notification-menu">
								<div class="notification-title">
									<span class="pull-right label label-default">230</span>
									Messages
								</div>
			
								<div class="content">
									<ul>
										<li>
											<a href="#" class="clearfix">
												<figure class="image">
													<img src="{{ asset('/admin_resource/')}}/assets/images/!sample-user.jpg" alt="Joseph Doe Junior" class="img-circle" />
												</figure>
												<span class="title">Joseph Doe</span>
												<span class="message">Lorem ipsum dolor sit.</span>
											</a>
										</li>
										<li>
											<a href="#" class="clearfix">
												<figure class="image">
													<img src="{{ asset('/admin_resource/')}}/assets/images/!sample-user.jpg" alt="Joseph Junior" class="img-circle" />
												</figure>
												<span class="title">Joseph Junior</span>
												<span class="message truncate">Truncated message. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sit amet lacinia orci. Proin vestibulum eget risus non luctus. Nunc cursus lacinia lacinia. Nulla molestie malesuada est ac tincidunt. Quisque eget convallis diam, nec venenatis risus. Vestibulum blandit faucibus est et malesuada. Sed interdum cursus dui nec venenatis. Pellentesque non nisi lobortis, rutrum eros ut, convallis nisi. Sed tellus turpis, dignissim sit amet tristique quis, pretium id est. Sed aliquam diam diam, sit amet faucibus tellus ultricies eu. Aliquam lacinia nibh a metus bibendum, eu commodo eros commodo. Sed commodo molestie elit, a molestie lacus porttitor id. Donec facilisis varius sapien, ac fringilla velit porttitor et. Nam tincidunt gravida dui, sed pharetra odio pharetra nec. Duis consectetur venenatis pharetra. Vestibulum egestas nisi quis elementum elementum.</span>
											</a>
										</li>
										<li>
											<a href="#" class="clearfix">
												<figure class="image">
													<img src="{{ asset('/admin_resource/')}}/assets/images/!sample-user.jpg" alt="Joe Junior" class="img-circle" />
												</figure>
												<span class="title">Joe Junior</span>
												<span class="message">Lorem ipsum dolor sit.</span>
											</a>
										</li>
										<li>
											<a href="#" class="clearfix">
												<figure class="image">
													<img src="{{ asset('/admin_resource/')}}/assets/images/!sample-user.jpg" alt="Joseph Junior" class="img-circle" />
												</figure>
												<span class="title">Joseph Junior</span>
												<span class="message">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sit amet lacinia orci. Proin vestibulum eget risus non luctus. Nunc cursus lacinia lacinia. Nulla molestie malesuada est ac tincidunt. Quisque eget convallis diam.</span>
											</a>
										</li>
									</ul>
			
									<hr />
			
									<div class="text-right">
										<a href="#" class="view-more">View All</a>
									</div>
								</div>
							</div>
						</li>
						<li>
							<a href="#" class="dropdown-toggle notification-icon" data-toggle="dropdown">
								<i class="fa fa-bell"></i>
								<span class="badge">3</span>
							</a>
			
							<div class="dropdown-menu notification-menu">
								<div class="notification-title">
									<span class="pull-right label label-default">3</span>
									Alerts
								</div>
			
								<div class="content">
									<ul>
										<li>
											<a href="#" class="clearfix">
												<div class="image">
													<i class="fa fa-thumbs-down bg-danger"></i>
												</div>
												<span class="title">Server is Down!</span>
												<span class="message">Just now</span>
											</a>
										</li>
										<li>
											<a href="#" class="clearfix">
												<div class="image">
													<i class="fa fa-lock bg-warning"></i>
												</div>
												<span class="title">User Locked</span>
												<span class="message">15 minutes ago</span>
											</a>
										</li>
										<li>
											<a href="#" class="clearfix">
												<div class="image">
													<i class="fa fa-signal bg-success"></i>
												</div>
												<span class="title">Connection Restaured</span>
												<span class="message">10/10/2014</span>
											</a>
										</li>
									</ul>
			
									<hr />
			
									<div class="text-right">
										<a href="#" class="view-more">View All</a>
									</div>
								</div>
							</div>
						</li>
					</ul>
			
					<span class="separator"></span>
			
					<div id="userbox" class="userbox">
						<a href="#" data-toggle="dropdown">
							<figure class="profile-picture">
								<img src="{{ asset('/admin_resource/')}}/assets/images/!logged-user.jpg" alt="Joseph Doe" class="img-circle" data-lock-picture="{{ asset('/admin_resource/')}}/assets/images/!logged-user.jpg" />
							</figure>
							<div class="profile-info" data-lock-name="John Doe" data-lock-email="johndoe@JSOFT.com">
								<span class="name">Admin</span>
							</div>
			
							<i class="fa custom-caret"></i>
						</a>
			
						<div class="dropdown-menu">
							<ul class="list-unstyled">
								<li class="divider"></li>
								<li>
									<a role="menuitem" tabindex="-1" href="pages-user-profile.html"><i class="fa fa-user"></i> My Profile</a>
								</li>

	<li class="nav-item ">
         <a class="dropdown-item" href="{{ route('logout') }}"
               onclick="event.preventDefault();
                             document.getElementById('logout-form').submit();">
                             <i class="fa fa-power-off"></i>
                {{ __('Logout') }}
            </a>

            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                @csrf
            </form>
      </li>
							</ul>
						</div>
					</div>
				</div>
				<!-- end: search & user box -->
			</header>
			<!-- end: header -->

resources/views/Admin/common/sidebar.blade.php
<!-- start: sidebar -->
<aside id="sidebar-left" class="sidebar-left">

	<div class="sidebar-header">
		{{-- <div class="sidebar-title">
			Navigation
		</div> --}}
		<div class="sidebar-toggle hidden-xs" data-toggle-class="sidebar-left-collapsed" data-target="html" data-fire-event="sidebar-left-toggle">
			<i class="fa fa-bars" aria-label="Toggle sidebar"></i>
		</div>
	</div>

	<div class="nano">
		<div class="nano-content">
			<nav id="menu" class="nav-main" role="navigation">
				<ul class="nav nav-main">
					<li class="nav-active">
						<a href="{{url('/dashboard')}}">
							<i class="fa fa-home" aria-hidden="true"></i>
							<span>Dashboard</span>
						</a>
					</li>

					<li class="nav-parent">
						<a>
							<i class="fa fa-user" aria-hidden="true"></i>
							<span>User</span>
						</a>
						<ul class="nav nav-children">

							{{-- 	<a href="{{route('users.create')}}">
									 Add User
								</a> --}}
								 <router-link :to="{ name: 'add-user' }" class="{{ (request()->is('page')) ? 'nav-item  active' : '' }}">Add User</router-link>
						

							<li>
								<a href="{{route('users.index')}}">
									 User List
								</a>
							</li>
						
						</ul>
					</li>

					<li class="nav-parent">
						<a>
							<i class="fa fa-user" aria-hidden="true"></i>
							<span>Permission Manage</span>
						</a>
						<ul class="nav nav-children">

							<li class="{{ (request()->is('permissions')) ? 'nav-item  active' : '' }}">
								<a href="{{route('permissions.create')}}">
									 Add Permission
								</a>
							</li>

							<li>
								<a href="{{route('permissions.index')}}">
									  Permission List
								</a>
							</li>
						
						</ul>
					</li>
					<li class="nav-parent">
						<a>
							<i class="fa fa-user" aria-hidden="true"></i>
							<span>Role Manage</span>
						</a>
						<ul class="nav nav-children">

							<li class="{{ (request()->is('page')) ? 'nav-item  active' : '' }}">
								<a href="{{route('roles.create')}}">
									 Add Role
								</a>
							</li>

							<li>
								<a href="{{route('roles.index')}}">
									 Role List
								</a>
							</li>
						
						</ul>
					</li>

					<li class="nav-parent {{ (request()->is('page/create*')) ||  (request()->is('page/create*'))  ? 'active menu-open' : '' }}">
						<a>
							<i class="fa fa-copy" aria-hidden="true"></i>
							<span>Pages</span>
						</a>
						<ul class="nav nav-children">

							<li class="nav-item {{ (request()->is('page/create')) ||  (request()->is('page/create*'))  ? 'active menu-open' : '' }}">
								<a href="{{ route('page.create')}}" class="{{ (request()->is('page/create')) ? 'nav-item  nav-active' : '' }}">
									<i class="fa fa-plus"></i>
									 Add Page
								</a>
							</li>

							<li>
								<a href="{{route('page.index')}}">
									<i class="fa fa-list"></i> Page List
								</a>
							</li>

						
						</ul>
					</li>
					<li class="nav-parent">
						<a>
							<i class="fa fa-tasks" aria-hidden="true"></i>
							<span>Category</span>
						</a>
						<ul class="nav nav-children">
							<li>
								<a href="{{route('category.create')}}">
									<i class="fa fa-plus"></i> Add Category
								</a>
							</li>
							<li>
								<a href="{{route('category.index')}}">
									<i class="fa fa-list"></i> Category List
								</a>
							</li>
							
						</ul>
					</li>
					<li class="nav-parent">
						<a>
							<i class="fa fa-list-alt" aria-hidden="true"></i>
							<span>Post</span>
						</a>
						<ul class="nav nav-children">
							<li>
								<a href="{{route('post.create')}}">
									 Add Post
								</a>
							</li>
							<li>
								<a href="{{route('post.index')}}">
									  Post List
								</a>
							</li>
						</ul>
					</li>
	
					
					<li class="nav-parent">
						<a>
							<i class="fa fa-table" aria-hidden="true"></i>
							<span>Menu</span>
						</a>
						<ul class="nav nav-children">
							<li>
								<a href="tables-basic.html">
									 Basic
								</a>
							</li>
							<li>
								<a href="tables-advanced.html">
									 Advanced
								</a>
							</li>
						</ul>
					</li>
					<li class="nav-parent">
						<a>
							<i class="fa fa-table" aria-hidden="true"></i>
							<span>Tag</span>
						</a>
						<ul class="nav nav-children">
							<li>
								<a href="tables-basic.html">
									 Basic
								</a>
							</li>
							<li>
								<a href="tables-advanced.html">
									 Advanced
								</a>
							</li>
						</ul>
					</li>
					<li>
						<a>
							<i class="fa fa-table" aria-hidden="true"></i>
							<span>Settings</span>
						</a>
					</li>
				</ul>
			</nav>

			<hr class="separator" />

		</div>

	</div>

</aside>
<!-- end: sidebar -->